import { change, consumption, expectedCash, money, totals } from '../domain/calculate'
import type { Draft, Identity, MenuItem, Operation, OpKind, Order, Settings, Shift, StockItem } from '../domain/types'
import { MejaDB, uid } from './db'
export class Commands {
 constructor(public db:MejaDB,public user:Identity){}
 async run<T>(kind:OpKind, payload:Record<string,unknown>, mutate:(op:Operation)=>Promise<T>):Promise<T>{
  if(!this.user.primary)throw new Error('Transaksi hanya di perangkat kasir utama')
  const op:Operation={id:uid(),kind,actor:this.user.id,restaurantId:this.user.restaurantId,deviceId:this.user.deviceId,occurredAt:new Date().toISOString(),payload,state:'pending',attempts:0,nextAttempt:0}
  try{return await this.db.transaction('rw',this.db.tables,async()=>{const result=await mutate(op);await this.db.outbox.add(op);return result})}catch(e){throw new Error(e instanceof Error?e.message:'Penyimpanan gagal. Jangan tutup halaman; ekspor pemulihan.')}
 }
 manager(online=false){if(this.user.role==='cashier')throw new Error('Perlu akun manajer');if(online&&!this.user.demo&&!navigator.onLine)throw new Error('Tindakan ini perlu koneksi server')}
 async shift(){const s=await this.db.shifts.where('status').equals('open').first();if(!s||s.actor!==this.user.id)throw new Error('Buka sif Anda terlebih dahulu');if(Date.now()>Date.parse(s.expiresAt))throw new Error('Otorisasi sif berakhir. Hubungkan internet dan tutup sif.');return s}
 async openShift(opening:number){money(opening);const id=uid();return this.run('shift.open',{id,opening},async op=>{if(await this.db.shifts.where('status').equals('open').count())throw new Error('Sif masih terbuka');const shift:Shift={id,actor:this.user.id,cashier:this.user.name,openedAt:op.occurredAt,expiresAt:new Date(Date.parse(op.occurredAt)+12*3600000).toISOString(),opening,status:'open'};await this.db.shifts.add(shift);return shift})}
 async save(draft:Draft){return this.run('order.save',{draft},async op=>{
  const shift=await this.shift();if(!draft.lines.some(l=>!l.cancelled))throw new Error('Tambahkan menu dahulu')
  const old=draft.orderId?await this.db.orders.get(draft.orderId):undefined
  if(draft.orderId&&!old)throw new Error('Pesanan tidak ditemukan')
  if(old&&(old.status!=='open'||old.revision!==draft.revision))throw new Error('Pesanan sudah berubah. Buka ulang dari Pesanan.')
  if(draft.discount!== (old?.discount||0)){this.manager();if(draft.discount&&!draft.discountReason.trim())throw new Error('Isi alasan diskon')}
  const settings=old?.settings||await this.db.settings.get('settings');if(!settings)throw new Error('Selesaikan pengaturan restoran')
  if(old)for(const line of old.lines.filter(l=>l.prepared)){const next=draft.lines.find(l=>l.id===line.id);if(!next||JSON.stringify(next)!==JSON.stringify(line))throw new Error('Menu yang sudah disiapkan tidak dapat diubah. Batalkan seluruh pesanan dengan alasan.')}
  for(const l of draft.lines){if(!Number.isInteger(l.qty)||l.qty<1||l.qty>999)throw new Error('Jumlah menu 1–999');money(l.price)}
  const order:Order={id:old?.id||uid(),restaurantId:this.user.restaurantId,shiftId:shift.id,actor:this.user.id,cashier:this.user.name,revision:(old?.revision||0)+1,receiptId:old?.receiptId||`MJ-${op.id.toUpperCase()}`,label:draft.label,mode:draft.mode,lines:draft.lines,status:'open',prep:old?.prep||'new',discount:draft.discount,discountReason:draft.discountReason,settings,totals:totals(draft.lines,draft.discount,settings),createdAt:old?.createdAt||op.occurredAt,updatedAt:op.occurredAt}
  op.payload={order,expectedRevision:old?.revision||0};await this.db.orders.put(order);await this.db.drafts.delete('current');return order
 })}
 async prepare(id:string){return this.run('order.prepare',{id},async op=>{await this.shift();const o=await this.openOrder(id);const lines=o.lines.filter(l=>!l.prepared&&!l.cancelled);if(!lines.length)throw new Error('Tidak ada tambahan baru untuk disiapkan');op.payload={id,expectedRevision:o.revision,lineIds:lines.map(l=>l.id)}
 for(const c of consumption(lines,o.mode==='takeaway'?o.settings.packaging:[]))await this.db.movements.add({id:`${op.id}-${c.stockId}`,stockId:c.stockId,qty:-c.qty,kind:'preparation',reason:`Persiapan ${o.label||o.receiptId}`,actor:this.user.id,at:op.occurredAt,recordId:o.id,cost:0})
 o.lines=o.lines.map(l=>({...l,prepared:l.prepared||!l.cancelled}));o.prep='preparing';o.revision++;o.updatedAt=op.occurredAt;await this.db.orders.put(o);return o})}
 async ready(id:string){return this.run('order.ready',{id},async op=>{const o=await this.openOrder(id);op.payload={id,expectedRevision:o.revision};if(o.lines.some(l=>!l.prepared&&!l.cancelled))throw new Error('Kirim seluruh menu ke dapur dahulu');o.prep='ready';o.revision++;await this.db.orders.put(o)})}
 async pay(id:string,method:'cash'|'qris'|'card',tendered:number,verified:boolean){return this.run('payment.record',{id,method,tendered,verified},async op=>{await this.shift();const o=await this.openOrder(id);if(o.lines.some(l=>!l.prepared&&!l.cancelled))throw new Error('Kirim ke dapur sebelum pembayaran');if(method!=='cash'&&(!verified||!navigator.onLine))throw new Error('Periksa pembayaran pada aplikasi merchant saat online');const t=method==='cash'?money(tendered):o.totals.total;const c=change(o.totals.total,t);op.payload={...op.payload,expectedRevision:o.revision};o.payment={method,tendered:t,change:c,verified:method==='cash'||verified,at:op.occurredAt};o.status='paid';o.revision++;o.updatedAt=op.occurredAt;await this.db.orders.put(o);return o})}
 async voidOrder(id:string,reason:string){this.manager();if(!reason.trim())throw new Error('Alasan wajib');return this.run('order.void',{id,reason},async op=>{const o=await this.openOrder(id);op.payload={...op.payload,expectedRevision:o.revision};o.status='void';o.voidReason=reason;o.revision++;o.updatedAt=op.occurredAt;await this.db.orders.put(o)})}
 async refund(id:string,reason:string){this.manager(true);if(!reason.trim())throw new Error('Alasan wajib');return this.run('refund.record',{id,reason},async op=>{const o=await this.db.orders.get(id);if(!o||o.status!=='paid')throw new Error('Hanya transaksi lunas yang dapat dikembalikan');const s=await this.shift();if(s.id!==o.shiftId)throw new Error('MVP: pengembalian hanya dalam sif asal yang masih terbuka');op.payload={...op.payload,expectedRevision:o.revision};o.status='refunded';o.refund={reason,at:op.occurredAt,actor:this.user.id};o.revision++;await this.db.orders.put(o)})}
 async stockRecord(stockId:string,kind:'opening'|'purchase'|'waste'|'count'|'adjustment',qty:number,reason:string,cost=0,fromDrawer=false){this.manager();if(!reason.trim()||!Number.isSafeInteger(qty)||Math.abs(qty)>1e12)throw new Error('Jumlah/alasan tidak valid');money(cost);return this.run('stock.record',{stockId,kind,qty,reason,cost,fromDrawer},async op=>{
 if(!await this.db.stock.get(stockId))throw new Error('Bahan tidak ditemukan');const balance=(await this.db.movements.where('stockId').equals(stockId).toArray()).reduce((n,m)=>n+m.qty,0)
 const delta=kind==='count'?qty-balance:kind==='waste'?-Math.abs(qty):qty
 if((kind==='purchase'||kind==='opening')&&qty<=0)throw new Error('Jumlah harus positif')
 await this.db.movements.add({id:op.id,stockId,kind,qty:delta,reason,actor:this.user.id,at:op.occurredAt,recordId:op.id,cost});if(fromDrawer){const s=await this.shift();await this.db.cash.add({id:op.id,shiftId:s.id,amount:-cost,reason:`Pembelian: ${reason}`,at:op.occurredAt,actor:this.user.id,recordId:op.id});op.payload.shiftId=s.id}return delta})}
 async cashMove(amount:number,reason:string){if(!Number.isSafeInteger(amount)||!amount||Math.abs(amount)>1e9||!reason.trim())throw new Error('Jumlah/alasan tidak valid');return this.run('shift.cash',{amount,reason},async op=>{const s=await this.shift();op.payload.shiftId=s.id;await this.db.cash.add({id:op.id,shiftId:s.id,amount,reason,actor:this.user.id,at:op.occurredAt})})}
 async closeShift(counted:number){money(counted);return this.run('shift.close',{counted},async op=>{const s=await this.shift();const orders=await this.db.orders.where('shiftId').equals(s.id).toArray();if(orders.some(o=>o.status==='open'))throw new Error('Selesaikan atau batalkan pesanan belum dibayar');const expected=expectedCash(s,orders,await this.db.cash.toArray());Object.assign(s,{status:'closed',counted,expected,variance:counted-expected,closedAt:op.occurredAt});op.payload.id=s.id;await this.db.shifts.put(s);return s})}
 async publish(menu:MenuItem[],stock:StockItem[]){this.manager(true);return this.run('catalog.publish',{menu,stock},async()=>{await this.db.menu.clear();await this.db.menu.bulkPut(menu);await this.db.stock.bulkPut(stock)})}
 async settings(settings:Settings){this.manager(true);return this.run('settings.update',{settings},async()=>{await this.db.settings.put(settings)})}
 private async openOrder(id:string){const o=await this.db.orders.get(id);if(!o||o.status!=='open')throw new Error('Pesanan tidak terbuka');return o}
}
