// Generated by scripts/test-db.mjs from applied SQL migrations. Do not edit.
export type Json = string | number | boolean | null | { [key:string]: Json | undefined } | Json[]
export interface Database { public: { Tables: {
  cash_movements: { Row: {
    restaurant_id: string
    id: string
    shift_id: string
    amount: number
    reason: string
    actor: string
    occurred_at: string
    purchase_id: string | null
  }; Insert: never; Update: never; Relationships: [] }
  catalog_items: { Row: {
    restaurant_id: string
    id: string
    version: number
  }; Insert: never; Update: never; Relationships: [] }
  catalog_versions: { Row: {
    restaurant_id: string
    item_id: string
    version: number
    snapshot: Json
    created_at: string
  }; Insert: never; Update: never; Relationships: [] }
  device_handovers: { Row: {
    id: string
    restaurant_id: string
    old_device: string
    new_device: string
    actor: string
    note: string
    at: string
  }; Insert: never; Update: never; Relationships: [] }
  devices: { Row: {
    restaurant_id: string
    id: string
    enrolled_by: string
    enrolled_at: string
    revoked_at: string | null
  }; Insert: never; Update: never; Relationships: [] }
  inventory_items: { Row: {
    restaurant_id: string
    id: string
    name: string
    unit: string
    threshold: number
  }; Insert: never; Update: never; Relationships: [] }
  memberships: { Row: {
    restaurant_id: string
    user_id: string
    role: string
    name: string
    active: boolean
  }; Insert: never; Update: never; Relationships: [] }
  order_lines: { Row: {
    restaurant_id: string
    order_id: string
    id: string
    item_id: string
    catalog_version: number
    snapshot: Json
  }; Insert: never; Update: never; Relationships: [] }
  orders: { Row: {
    restaurant_id: string
    id: string
    shift_id: string
    actor: string
    revision: number
    status: string
    created_at: string
    updated_at: string
    received_at: string
    snapshot: Json
  }; Insert: never; Update: never; Relationships: [] }
  payments: { Row: {
    restaurant_id: string
    order_id: string
    operation_id: string
    method: string
    total: number
    tendered: number
    change: number
    verified: boolean
    occurred_at: string
    received_at: string
    actor: string
  }; Insert: never; Update: never; Relationships: [] }
  preparations: { Row: {
    restaurant_id: string
    order_id: string
    line_id: string
    operation_id: string
    occurred_at: string
    actor: string
  }; Insert: never; Update: never; Relationships: [] }
  purchases: { Row: {
    restaurant_id: string
    id: string
    stock_id: string
    qty: number
    cost: number
    reason: string
    actor: string
    occurred_at: string
  }; Insert: never; Update: never; Relationships: [] }
  refunds: { Row: {
    restaurant_id: string
    order_id: string
    operation_id: string
    amount: number
    reason: string
    actor: string
    occurred_at: string
    received_at: string
  }; Insert: never; Update: never; Relationships: [] }
  restaurants: { Row: {
    id: string
    settings: Json
    primary_device_id: string | null
    created_at: string
  }; Insert: never; Update: never; Relationships: [] }
  shifts: { Row: {
    restaurant_id: string
    id: string
    actor: string
    device_id: string
    opened_at: string
    expires_at: string
    closed_at: string | null
    opening: number
    counted: number | null
    expected: number | null
    variance: number | null
    cashier: string
    catalog: Json
  }; Insert: never; Update: never; Relationships: [] }
  stock_balances: { Row: {
    restaurant_id: string | null
    stock_id: string | null
    qty: number | null
  }; Insert: never; Update: never; Relationships: [] }
  stock_movements: { Row: {
    restaurant_id: string
    id: string
    stock_id: string
    qty: number
    kind: string
    reason: string
    actor: string
    occurred_at: string
    received_at: string
    record_id: string
    operation_id: string
    cost: number
  }; Insert: never; Update: never; Relationships: [] }
  sync_operations: { Row: {
    id: string
    restaurant_id: string
    actor: string
    device_id: string
    kind: string
    payload: Json
    occurred_at: string
    received_at: string
    result: Json
  }; Insert: never; Update: never; Relationships: [] }
}; Views: Record<string, never>; Functions: { apply_operation: { Args: { operation: Json }; Returns: Json }; bootstrap: { Args: { device_id: string }; Returns: Json }; enroll_device: { Args: { device_id: string }; Returns: undefined }; manage_staff: { Args: { target: string; new_role: string; new_active: boolean }; Returns: undefined }; sales_report: { Args: { from_day: string; to_day: string }; Returns: Json } }; Enums: Record<string, never>; CompositeTypes: Record<string, never> } }
