import { test,expect,demo,openShift,addItem,cart } from './meja'
test('happy path: open shift, sell an item with a modifier, take cash, close the shift', async({page})=>{
 await demo(page)
 await openShift(page,'200000')
 await addItem(page,'Nasi goreng kampung',{eggs:true,note:'Tidak pedas, tanpa bawang'})
 await expect(cart(page).getByText('Tambah telur')).toBeVisible()
 await expect(cart(page).getByText('Tidak pedas, tanpa bawang')).toBeVisible()
 await expect(cart(page).locator('.bill-total')).toContainText(/Rp\s*30\.000/) // 25.000 + 5.000 telur
 await cart(page).getByRole('button',{name:/Ke dapur/}).click()
 await expect(cart(page).getByText(/Dikirim ke dapur/)).toBeVisible()
 await cart(page).getByRole('button',{name:/Lanjut pembayaran/}).click()
 const pay=page.getByRole('dialog',{name:'Terima pembayaran'})
 await expect(pay.locator('.payment-total')).toContainText(/Rp\s*30\.000/)
 await pay.getByLabel(/Uang diterima/).fill('50000')
 await expect(pay.locator('.bill-total')).toContainText(/Rp\s*20\.000/)
 await pay.getByRole('button',{name:/Catat pembayaran/}).click()
 const receipt=page.getByRole('dialog',{name:'Pembayaran tercatat'})
 await expect(receipt.locator('.receipt-total')).toContainText(/Rp\s*30\.000/)
 await expect(receipt.locator('.receipt-sums')).toContainText(/Kembalian/)
 await expect(receipt.locator('.receipt-sums')).toContainText(/Rp\s*20\.000/)
 await receipt.getByRole('button',{name:'Tutup'}).click()
 await page.locator('.sidebar').getByRole('link',{name:'Laporan'}).click()
 await expect(page.getByRole('heading',{name:'Laporan & kas'})).toBeVisible()
 await expect(page.locator('.panel').filter({hasText:'Laci kas'}).locator('.bill-total')).toContainText(/Rp\s*230\.000/) // 200.000 modal + 30.000 tunai
 await page.getByRole('button',{name:'Tutup sif'}).click()
 const closing=page.getByRole('dialog',{name:'Tutup sif'})
 await closing.getByLabel(/Uang tunai yang dihitung/).fill('225000')
 await expect(closing.locator('.bill-total')).toContainText(/Rp\s*5\.000/)
 await expect(closing.locator('.bill-total')).toContainText('-')
 await closing.getByRole('button',{name:'Konfirmasi tutup sif'}).click()
 await expect(closing).toBeHidden()
 await expect(page.getByText('Tidak ada sif aktif')).toBeVisible()
 await expect(page.locator('.history-list')).toContainText(/Dihitung Rp\s*225\.000/)
 await expect(page.locator('.history-list')).toContainText(/Selisih -Rp\s*5\.000/)
})
test('an unpaid order can be saved and reopened from Pesanan', async({page})=>{
 await demo(page)
 await openShift(page)
 await cart(page).getByLabel(/Meja \/ nama pesanan/).fill('Meja 03')
 await addItem(page,'Es teh manis')
 await cart(page).getByRole('button',{name:/Simpan/}).click()
 await expect(cart(page).getByText('Pesanan tersimpan')).toBeVisible()
 await page.locator('.sidebar').getByRole('link',{name:'Pesanan'}).click()
 const card=page.locator('.order-card').filter({hasText:'Meja 03'})
 await expect(card).toContainText('Belum dibayar')
 await expect(card).toContainText('Es teh manis')
 await card.getByRole('button',{name:/Buka pesanan/}).click()
 await expect(page).toHaveURL(/\/pos$/)
 await expect(cart(page).getByLabel(/Meja \/ nama pesanan/)).toHaveValue('Meja 03')
 await expect(cart(page).getByText('Es teh manis')).toBeVisible()
 await expect(cart(page).locator('.bill-total')).toContainText(/Rp\s*6\.000/)
})
test('the draft cart survives a page reload', async({page})=>{
 await demo(page)
 await addItem(page,'Es teh manis')
 await addItem(page,'Kentang goreng')
 await cart(page).getByLabel(/Meja \/ nama pesanan/).fill('Meja 07')
 await expect(cart(page).locator('.bill-total')).toContainText(/Rp\s*21\.000/)
 await page.reload()
 await expect(page.getByRole('heading',{name:'Kasir',level:1})).toBeVisible()
 await expect(cart(page).getByText('Es teh manis')).toBeVisible()
 await expect(cart(page).getByText('Kentang goreng')).toBeVisible()
 await expect(cart(page).getByLabel(/Meja \/ nama pesanan/)).toHaveValue('Meja 07')
 await expect(cart(page).locator('.bill-total')).toContainText(/Rp\s*21\.000/)
})
