import { useState } from 'react'
import { Printer,Copy,Check } from 'lucide-react'
import { useApp } from '../../app/context'
import type { Order } from '../../domain/types'
import { Dialog } from '../../components/ui/dialog'
import { Button } from '../../components/ui/button'
import { browserPrinter,receiptText } from '../../lib/printer'
import { uid } from '../../lib/db'
export function Receipt({order,onClose,kitchen=false,reprint=false}:{order:Order;onClose:()=>void;kitchen?:boolean;reprint?:boolean}){
 const {db,act,busy,setNotice}=useApp();const [attempt,setAttempt]=useState<string>();const [fallback,setFallback]=useState('');const [printedLines,setPrintedLines]=useState<string[]>([])
 const text=receiptText(order,reprint)
 async function print(){await act(async()=>{const old=await db.prints.where('orderId').equals(order.id).toArray();const known=new Set(old.filter(p=>p.kind==='kitchen').flatMap(p=>p.lineIds));const lines=order.lines.filter(l=>!known.has(l.id));setPrintedLines(lines.map(l=>l.id));const id=uid();await db.prints.add({id,orderId:order.id,kind:kitchen?'kitchen':'receipt',at:new Date().toISOString(),status:'requested',reprint,lineIds:lines.map(l=>l.id)});setAttempt(id);await new Promise(resolve=>setTimeout(resolve,50));await browserPrinter.requestPrint()},'Permintaan cetak dicatat. Periksa hasil kertas.')}
 async function share(){try{if(navigator.share)await navigator.share({text});else{await navigator.clipboard.writeText(text);setNotice('Teks struk disalin')}}catch{setFallback(text)}}
 return <Dialog open onOpenChange={onClose} title={kitchen?'Tiket dapur':reprint?'Salinan struk':'Pembayaran tercatat'} description="Pratinjau cetak. Hasil kertas perlu diperiksa oleh operator."><div id="print-area" className="receipt-paper" style={{'--paper-width':`${order.settings.receiptWidth}mm`,'--printable-width':`${order.settings.printableWidth}mm`} as React.CSSProperties}>{kitchen?<><h2>{order.status==='void'?'PEMBATALAN':'DAPUR'} {reprint?'— SALINAN':''}</h2><h2>{order.label||order.receiptId.slice(-8)}</h2><p>{order.mode==='dinein'?'Makan di sini':'Bungkus'} · {new Date(order.updatedAt).toLocaleTimeString('id-ID',{timeZone:order.settings.timezone})}</p>{order.lines.filter(l=>!l.cancelled).map(l=><div className="kitchen-line" key={l.id}><strong>{l.qty}× {l.name}</strong>{printedLines.includes(l.id)&&<b> [BARU]</b>}<p>{l.modifiers.map(m=>m.name).join(', ')}</p><b>{l.note}</b></div>)}{order.voidReason&&<p>Alasan: {order.voidReason}</p>}<p>Periksa tambahan terhadap tiket sebelumnya. Jangan menyiapkan salinan dua kali.</p></>:<pre>{text}</pre>}</div><div className="button-row"><Button disabled={busy} onClick={()=>void print()}><Printer size={17}/> Cetak {kitchen?'tiket':'struk'}</Button>{!kitchen&&<Button variant="secondary" onClick={()=>void share()}><Copy size={16}/> Bagikan teks</Button>}</div>{attempt&&<><p className="callout">Cetak diminta, belum berarti kertas tercetak. Jika dialog dibatalkan, transaksi tetap tersimpan.</p><Button variant="secondary" disabled={busy} className="full" onClick={()=>void act(async()=>{await db.prints.update(attempt,{status:'confirmed'});setAttempt(undefined)},'Hasil cetak dikonfirmasi operator')}><Check size={17}/> Saya sudah melihat hasil cetak</Button></>}{fallback&&<label>Salin teks struk<textarea readOnly value={fallback} rows={6}/></label>}</Dialog>
}
